Extended responseDecodable for JSONDecoder injection
PromiseKit/Alamofire- pull request #24
Opened 2018-02-25 21:18 UTC by timbms

And also added test for responseDecodable

2018-02-25 22:44 UTC, mxcl requested changes
Great! Two minor issues.

2018-02-25 22:44 UTC, mxcl commented on Sources/Alamofire+Promise.swift
> +     Returns a Promise for a DecJodable
typo

2018-02-25 22:44 UTC, mxcl commented on Sources/Alamofire+Promise.swift
> +                    } catch let error {
this is an unnecessary addition

2018-02-25 22:45 UTC, mxcl commented
Also, tests require a `swift(>=3.2)` guard.

2018-02-26 10:43 UTC, timbms commented
Done and committed
It is not clear to me how I can run Travis CI on it.


Sent from my iPhone

> On 25. Feb 2018, at 23:45, Max Howell <notifications@github.com> wrote:
> 
> Also, tests require a swift(>=3.2) guard.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2018-03-03 04:18 UTC, mxcl commented
Sorry somehow I missed your commit.

> It is not clear to me how I can run Travis CI on it.

Travis runs automatically.

2018-03-03 04:18 UTC, mxcl approved these changes

2018-03-03 04:18 UTC, merged